[build]
command = "npm run build"
output_directory = "dist"
base_directory = ""

[build.environment]
NODE_VERSION = "18"

[site]
bucket = "./dist"
entry-point = "workers-site"

[env.production]
name = "eyeunit"
route = "eyeunit.pages.dev/*"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200 